sudo: required
language: generic

services:
  - docker

before_install:
  - docker build  -t cloudpg07/docker-react-01 -f Dockerfile.dev .

script:
  - docker run -e CI=true cloudpg07/docker-react-01 npm run test

# Setting up the aws beanstalk
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-01"
  env: "Dockerreact01-env"
  bucket_name: "elasticbeanstalk-us-east-2-362076328835"
  bucket_path: "docker-react-01"

  # Only push the code to aws when there is change in the master branch
  on:
    branch: master
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY